../MAIN.pdf :: agradecimientos.tex  Introduction.tex  resultados.tex Conclusiones.tex     marcoTeorico.tex  symbol.tex FuzzyMeasure.tex     Objetivos.tex     title.tex
	cd .. && make MAIN.pdf
-include ~/makefile
