MAIN.pdf :: Sections/Conclusiones.tex Sections/FuzzyMeasurement.tex Sections/Objetivos.tex Sections/title.tex Sections/DensityOperator.tex Sections/Introduction.tex Sections/POVM.tex Sections/Example_section.tex Sections/Justificacion.tex Sections/QuantumOperators.tex


-include ~/makefile
