MAIN.pdf :: MAIN.tex Sections/agradecimientos.tex  Sections/marcoTeorico.tex Sections/Conclusiones.tex     Sections/Objetivos.tex Sections/symbol.tex Sections/title.tex Sections/Introduction.tex Sections/FuzzyMeasure.tex


-include ~/makefile
