MAIN.pdf :: MAIN.tex Sections/agradecimientos.tex  Sections/marcoTeorico.tex Sections/Conclusiones.tex     Sections/Objetivos.tex Sections/FM2particulas.tex    Sections/symbol.tex Sections/FMnParticulas.tex    Sections/title.tex Sections/Introduction.tex


-include ~/makefile
